### ISSUE TITLE
Elasticsearch 2.x support?

### ISSUE THREAD

**Issue by lextoumbourou** [lextoumbourou/txes2#9]
txes2 currently doesn't support Elasticsearch 2.x, this issue will look into what needs to be done to make it happen.

**Comment by luismartingil** [comment]
Do you know what changes in the 2.X are not compatible with the library?

**Comment by lextoumbourou** [comment]
Starting digging into this tonight. Here's the list of things I've found so far. I'm sure there'll be more.
1. Errors are returned in a completely different format (See [ES PR](http://github.com/elastic/elasticsearch/issues/10643)). [Our exception handling code](https://github.com/lextoumbourou/txes2/blob/master/txes2/exceptions.py#L84) will need to be updated to support them.
   
   Example of errors in ES 1.7
   
   ```
   curl http://localhost:9201/_nothing
   {"error":"ElasticsearchIllegalArgumentException[No feature for name [_nothing]]","status":400}
   ```
   
   Errors in ES 2.x
   
   ```
   curl http://localhost:9200/_nothing
   {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No feature for name [_nothing]"}],"type":"illegal_argument_exception","reason":"No feature for name [_nothing]"},"status":400}
   ```
2. Need to update `status` method (and probably rename it) to utilise `_stats` instead of `_status` as it has been removed (see [ES PR](http://github.com/elastic/elasticsearch/issues/6062)). This affect `get_alias` and `get_indices`.
3. Rivers are long dead (see [ES PR](http://github.com/elastic/elasticsearch/issues/11568)). Let's remove all references to them.

**Comment by anekix** [comment]
any progress on this?is v2.x supported now? beacause i see a lot of demand for twisted + elastic

**Comment by lextoumbourou** [comment]
Txes2 now supports ES 2.x as of version ``2.0.0``. Right on time for it's EOL :laughing: 

Apologies this took way too long - finding it very hard to make time for open-source right now.

:heart:
